### PR TITLE
Windows build mike

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
supersedes https://github.com/conda-forge/gawk-feedstock/pull/17

**Comment by mikemhenry** [comment]
hmm,
```
./regcomp.c:881:52: error: use of undeclared identifier '_NL_CTYPE_MAP_TO_NONASCII'
  dfa->map_notascii = (_NL_CURRENT_WORD (LC_CTYPE, _NL_CTYPE_MAP_TO_NONASCII)
  
./regcomp.c:879:41: error: use of undeclared identifier '_NL_CTYPE_CODESET_NAME'
      && strcmp (_NL_CURRENT (LC_CTYPE, _NL_CTYPE_CODESET_NAME), "UTF-8") == 0)
```

I wonder if something is wrong with the patch `0006-conditionally_disable_langinfo.patch` since the patch "patches" the part of the code throwing the error.

**Comment by mikemhenry** [comment]
Without the patch
```
In file included from regex.c:70:
./regex_internal.h:28:10: fatal error: 'langinfo.h' file not found
#include <langinfo.h>
         ^~~~~~~~~~~~
1 error generated.
```

So we do need the patch, just not sure how to fix it

**Comment by bollwyvl** [comment]
noted on [https://github.com/conda-forge/plumed-feedstock/pull/32 that ](https://github.com/conda-forge/plumed-feedstock/pull/32#issuecomment-1227845417) that you might be able to use `m2-gawk`: since it's already a per-platform build, it wouldn't be that big of a complication.

**Comment by mikemhenry** [comment]
I don't think I need this anymore, good luck to the next person to figure this out.

**Pull request closed without merging**
